version: "3.8"

services:
  ripe_DB:
    container_name: SEC_DB
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: S3c
      POSTGRES_DB: beautiful_db
    volumes:
      - ./SEC_DB:/var/lib/postgresql/data\
